name: Build Standalone CLI

on:
  push:
    tags:
      - 'v*'

env:
  CI: true

permissions:
  contents: read

jobs:
  build_cli:
    permissions:
      contents: write 
    runs-on: macos-11
    steps:
      - uses: actions/checkout@v2

      - run: git fetch --tags -f

      - name: Resolve version
        id: vars
        run: echo "::set-output name=tag_name::$(git describe --tags --abbrev=0)"

      - name: Use Node.js 16
        uses: actions/setup-node@v2
        with:
          node-version: '16'
          registry-url: 'https://registry.npmjs.org'
     

      - name: Install standalone cli 
        run: npm install
        
      - name: Lint standalone cli 
        run: npm run lint

      - name: Build standalone cli
        run: npm run build


    
